### ISSUE TITLE
provide a setting to disable the gradient in the 1.x version

### ISSUE THREAD

**Issue by zenoven** [equinusocio/vsc-material-theme-icons#100]
hi~~ I love the old version like 0.12 so much, it works great with the  [Palenight Theme](https://github.com/whizkydee/vscode-material-palenight-theme) color theme.

Since recent 1.x updates, the coloring scheme and the gradient on icon changed which I really think not suitable for a Material theme.

I  know it's possible to set to the older version like 0.12, but it's really strange for a Material theme to have gradient on icons.

**Comment by equinusocio** [comment]
Hi @zenoven, the new icons just introduce the finish layer spec provided by material design. There not gradients, just lights. More info here:

https://material.io/design/iconography/product-icons.html#specs

**Comment by zenoven** [comment]
so sorry for my misunderstanding, I know little about the spec.

it really looks like gradient as the icons are very small. 

And in icons in the red boxes and in the blue ones looks really not match as all the icons in the blue boxes flat, but the old version don't have this issue

![image](https://user-images.githubusercontent.com/1305982/58951421-abab1800-87c3-11e9-9cc8-b47e802d200a.png)

![image](https://user-images.githubusercontent.com/1305982/58951547-fa58b200-87c3-11e9-8a2d-9b3d89c2e8f1.png)

**Comment by teohhanhui** [comment]
They look ugly. That's all I know. Please provide an option to disable this "finish", or provide a flat variant of the icons.

**Comment by equinusocio** [comment]
Reverse to flat icons since no one like them 👍
