### ISSUE TITLE
Webpack icon for ts config files OR user icon customization settings option

### ISSUE THREAD

**Issue by polypus74** [equinusocio/vsc-material-theme-icons#13]
Webpack configuration files can be written in several languages, including typescript, but the typescript icon does not show up on filenames like: webpack.ts, webpack.config.ts, etc.

Is it, or could it be possible to set these as regexps in `src/icons/partials/fileNames.js`?
Either way, I'd like to request that the ts file names be added.

Alternatively, it would be great if there were a general solution in the form of a user settings option, something like:

`"materialTheme.iconsForFileNames": { "webpack.config.ts": "_file_webpack", ...}`

Allowing regexps in filename position would be a cherry on top.

**Comment by polypus74** [comment]
[As listed here](https://webpack.js.org/configuration/configuration-languages/), webpack also supports coffeescript. So the following would seem to do it:
```
  "webpack.config.ts": "_file_webpack",
  "webpack.dev.ts": "_file_webpack",
  "webpack.prod.ts": "_file_webpack",
  "webpack.common.ts": "_file_webpack",
  "webpackfile.ts": "_file_webpack",
  "webpack.ts": "_file_webpack",
  "webpack.config.coffee": "_file_webpack",
  "webpack.dev.coffee": "_file_webpack",
  "webpack.prod.coffee": "_file_webpack",
  "webpack.common.coffee": "_file_webpack",
  "webpackfile.coffee": "_file_webpack",
  "webpack.coffee": "_file_webpack",
```
Thanks :)

**Comment by equinusocio** [comment]
This issue has been fixed in the main repository but not yet released. We are going to separate the icons from the theme next weeks.
