### ISSUE TITLE
Duplicated icon themes

### ISSUE THREAD

**Issue by equinusocio** [equinusocio/vsc-material-theme-icons#24]
Duplicated icon themes when **Material Theme Icons** and **Material Theme <=2.6.3 (pre icons)** are both installed.
<img width="597" alt="screenshot 2019-02-08 at 14 58 34" src="https://user-images.githubusercontent.com/10454741/52482734-544cc080-2bb2-11e9-9886-8abdd780ab2c.png">

**Comment by equinusocio** [comment]
@LasaleFamine I think we can find a way to hide Material Theme Icons for who have Material Theme 2.6.3 or lower.

**Comment by LasaleFamine** [comment]
This will not happen with the new release of the Material Theme.
