### ISSUE TITLE
No Palenight Icon Theme

### ISSUE THREAD

**Issue by howardjohn** [equinusocio/vsc-material-theme-icons#42]
Before this repo was broken out, I was using `eq-material-theme-icons-palenight` as my icon theme. It seems like this theme no longer exists? Is there any way to access this theme now?

Its possible my install is messed up too - my icons completely disappeared today and I had to manually install this extension to get the icons back.

**Comment by LasaleFamine** [comment]
Hi @howardjohn, thank you for using the Material Theme Icons, firstly.

I want to make sure you know that the icons were removed from the Material Theme and published as separate extension (that point to this repository).

I think you should just make sure to install the [correct Material Theme Icons](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons) and run the `Fix` command from VSCode. Plus you can now choose whatever Icon Theme you like for your Material Theme variant.

Let us know if you have some other issue. I'm closing this one for now.

**Comment by howardjohn** [comment]
Ah I somehow got the wrong package. Thanks for the great theme! It is working perfectly now.
