### ISSUE TITLE
Road to release

### ISSUE THREAD

**Issue by LasaleFamine** [equinusocio/vsc-material-theme-icons#9]
This is what should be done before the first release:

- [x] `fixIcons` command that can fix the icons in relation of the current Material Theme variant (if installed and active for the user) (Darker, Ocean etc) and current accent (Acid Lime, Blue etc).
- [x] `fixIcons` should take care of hiding the command with the `when` option if the theme is not installed.
- [x] remove all icons' related things on `Material Theme`
- [x] update fixes to Material Theme
- [x] show initial notification if Material Theme not installed with the link
- [ ] (?)

***This post will be updated with other steps.***

**Comment by equinusocio** [comment]
@LasaleFamine ?
