### ISSUE TITLE
cargo.lock (and I'm guessing other *.lock files) show what looks like a Ruby icon

### ISSUE THREAD

**Issue by apersonnamedmike** [equinusocio/vsc-material-theme-icons#91]
![image](https://user-images.githubusercontent.com/10731372/57200984-ad2cba80-6f4f-11e9-9739-be797fd0b3fb.png)

Above is a partial screenshot showing what looks like the Ruby icon on one of my cargo.lock files. Is this correct?

**Comment by equinusocio** [comment]
Fixed in 1.0.4.
