### ISSUE TITLE
Unable to activate

### ISSUE THREAD

**Issue by vasilenka** [equinusocio/vsc-material-theme-icons#96]
After restarting code, file icons suddenly missing.
When I tried to fix the icon accent and re-activate it again, there's this error:

```
Unable to read file (Error: File not found (/Users/herlambang/.vscode/extensions/equinusocio.vsc-material-theme-icons-1.0.0/out/variants/Material-Theme-Icons-Darker.json))
```

I've tried disabling and reinstalling the extensions, and can't find any solution yet

**TEMP FIX - (EDIT BY AUTHOR)**
As temp fix, download this zip extract it, and move the `equinusocio.vsc-material-theme-icons-1.0.0` folder inside your extension folder. Make sure to delete other versions if present. Reload.

[equinusocio.vsc-material-theme-icons-1.0.0.zip](https://github.com/equinusocio/vsc-material-theme-icons/files/3227028/equinusocio.vsc-material-theme-icons-1.0.0.zip)

**Comment by equinusocio** [comment]
Hi @vasilenka we are sorry for this and we are investigating. As a temp fix, you can check inside the vscode extensions folder if you have the previous version `equinusocio.vsc-material-theme-icons-0.12.0`, then:

- Copy `equinusocio.vsc-material-theme-icons-0.12.0/out/variants` and `equinusocio.vsc-material-theme-icons-0.12.0/out/icons`
- Paste the two folders inside `equinusocio.vsc-material-theme-icons-1.0.0/out`
- Reload vscode.

**Comment by darthmeme** [comment]
I've got the same issue too, weirdly it only happened when I re-opened VSCode (it was fine until then). I don't have an older version so can't temp fix it 😞 

Thanks for the icon set though, it's awesome 🔥

**Comment by equinusocio** [comment]
Ok, download this zip extract it, and move the `equinusocio.vsc-material-theme-icons-1.0.0` folder inside your extension folder. Make sure to delete other versions if present.

[Uploading equinusocio.vsc-material-theme-icons-1.0.0.zip…]()

**Comment by hilleer** [comment]
The exact same thing happened to me as @darthmeme after reloading window, if that is any help.

**Comment by hLudde** [comment]
> Ca you guys test this packaged version? (Make sure to remove, for now, the one installed through the marketplace)
> 
> [vsc-material-theme-icons-1.0.1.vsix.zip](https://github.com/equinusocio/vsc-material-theme-icons/files/3228875/vsc-material-theme-icons-1.0.1.vsix.zip)

This worked for me ^^

**Comment by equinusocio** [comment]
Thank you. We will release it right.. now.

**Comment by hLudde** [comment]
hm, i downloaded the extension from the marketplace after i removed the packaged version i got and now it isnt working again :/

**Comment by equinusocio** [comment]
1.0.2 We have an issue with the vscode cli auto packaging, we have to package and publish manually.

**Comment by hLudde** [comment]
i see, yeah got 1.0.2 and its working now, awesome ^^

**Comment by hilleer** [comment]
I just installed version 1.0.4 from marketplace and confirm it works for me now :-)
